version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
platform: x64
install:
- pwsh: >-
    Invoke-WebRequest -Uri "https://win.rustup.rs/x86_64" -OutFile "$env:TEMP\rustup-init.exe"

    & "$env:TEMP\rustup-init.exe" -y --default-toolchain stable --profile minimal

    $env:Path = "$env:USERPROFILE\.cargo\bin;$env:Path"
build_script:
- pwsh: >-
    $env:Path = "$env:USERPROFILE\.cargo\bin;$env:Path"

    .\deployment\Build.ps1 -Verbose -Architecture x64 -InnoSetupPath "C:\Program Files (x86)\Inno Setup 6"

    .\deployment\Build.ps1 -Verbose -Architecture x86 -InnoSetupPath "C:\Program Files (x86)\Inno Setup 6"

artifacts:
- path: var/installer/svg_see_x64.exe
  name: installer 64bit
- path: var/installer/svg_see_x86.exe
  name: installer 32bit
